# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: kartevonmorken-dev

on:
  push:
    branches: [ develop ]

jobs:
  deploy:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: build
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
        run: |
          npm install -g yarn
          yarn install
          node server.build.dev.js
      - name: start
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
        run: |
          yarn add pm2
          pm2 restart pm2.config.js