# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: kartevonmorken-dev

on:
  push:
    branches: [ develop ]

jobs:
  deploy:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Install front-end dependancies
        run: |
          npm install -g yarn
          yarn install
          yarn add pm2
      - name: Build front-end
        run: |
          npm install -g yarn
          yarn install
          yarn build:dev
      - name: Start front-end
        run: pm2 restart pm2.config.js --only kartevonmorgen-dev
      - name: Setup python
        uses: actions/setup-python@v2
      - name: Install tag-synchronizer dependancies
        run: pip3 install -r scripts/python/requirements.txt
      - name: Run tag synchronizer
        run: pm2 restart pm2.config.js --only kartevonmorgen-tag-synchronizer-dev