#  https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/84

name: kartevonmorken-dev

on:
  push:
    branches: [ develop ]

jobs:
  deploy:

    runs-on: self-hosted

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'

      - name: Install front-end dependancies
        run: |
          npm install -g yarn
          yarn install

      - name: Install process manager
        run: yarn add pm2

      - name: Build front-end
        run: |
          yarn install
          yarn build:dev

      - name: Setup python
        uses: actions/setup-python@v2

      - name: Install tag-synchronizer dependancies
        working-directory: ./scripts/python
        run: pip3 install -r requirements.txt

      #     https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/84
      - name: Delete previous processes
        run: pm2 delete pm2.config.js

      - name: Start front-end
        run: pm2 start pm2.config.js --only kartevonmorgen-dev

      - name: Run tag synchronizer
        run: pm2 start pm2.config.js --only kartevonmorgen-tag-synchronizer-dev